#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

# create table commits(hash PRIMARY KEY, path TEXT, date TEXT, subject TEXT, lab TEXT, scientist TEXT, project TEXT);

function insert_commit ()
{
local date=`git log -1 --pretty=format:%ad`
local hash=`git log -1 --pretty=format:%h`
local subject=`git log -1 --pretty=format:%s`
local path=$PWD
local project=`basename $PWD`
local tmp=`dirname $PWD`
local scientist=`basename $tmp`
local tmp=`dirname $tmp`
local lab=`basename $tmp`
sqlite3 ${my_working}/projects.db "insert into commits (hash,path,date,subject,lab,scientist,project) values (\"$hash\",\"$path\",\"$date\",\"$subject\",\"$lab\",\"$scientist\",\"$project\");"
}
insert_commit




